name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'doc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Run tests
      run: 'make test'
